### PR TITLE
Correct typo: possesive -> possessive

### PR DESCRIPTION
**Pull request by felixonmars**
Needs https://github.com/Mikolaj/minimorph/pull/3

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Well spotted. Thank you.

**Comment by Mikolaj** [comment]
> Needs [Mikolaj/minimorph#3](https://github.com/Mikolaj/minimorph/pull/3)

I wonder, could you bump dependency on minimorph to strictly higher than the current version? I assume next version will contain your fix.

**Comment by felixonmars** [comment]
Updated :)

**Comment by Mikolaj** [comment]
Perfect. Thank you again.

**Pull request merged**
